### ISSUE TITLE
Flight form

### ISSUE THREAD

**Issue by Jefferyasbell** [Kleei/NerdPack-Kleei#1]
Hi was wondering if i am doing something wrong....If I toggle off travel form and I hit travel form manually I get dismounted and get put automatically in to moonkin form now I am using wow 7.3.5 everything works fine except that issue....do you think it is just the version of wow I am using? I also am using a generic unlocker as I have a mac and no one is making a platform that works on a mac

**Comment by Kleei** [comment]
Yo , as i understand you are using Druid - Balance rotation. No, this is not an issue , i made it like that.
Should i Remove ``/cancelform`` if you have travel form off ? And yeah , Balance Rotation is not complete yet, if you have any proposals we can make it better as my main is Rogue - Outlaw.

Join in our discord https://discord.gg/8ZbAZnc

**Comment by Kleei** [comment]
almost done,tonight i'll push the update.
